name: nucmc
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.13
  - pip
  # Build-time and C++ dependencies
  - pybind11
  - hdf5
  - pkg-config
  - cxx-compiler
  # Runtime dependencies (Conda versions)
  - pyyaml
  - numpy
  - scipy
  - pytest
  - pandas>=3.0
  - h5py
  - matplotlib
  - typer
  - rich
  - pyarrow
  # Documentation dependencies
  #- nbsphinx
  #- sphinx
  #- sphinx-rtd-theme
  #- myst-parser
  - pip:
    - -e .
variables:
  PYTHON_BASIC_REPL: "1"