[build-system]
requires = ["setuptools>=61.0", "wheel", "pybind11"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["nucmc"]

[project]
name = "nucmc"
version = "0.1.0"
requires-python = ">=3.13"
description = "Nucleosome Positioning Monte Carlo Simulation Suite"
dependencies = [
    "numpy",
    "pandas",
    "h5py",
    "typer",
    "rich",
    "pybind11",
    "matplotlib"
]

[project.scripts]
nucmc = "nucmc.cli:app"
